# Generated by Django 5.2.6 on 2025-09-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarintegration",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integrationlog",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.booking",
            ),
        ),
        migrations.AddField(
            model_name="integrationlog",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="videoconferenceintegration",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhookintegration",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="calendarintegration",
            index=models.Index(
                fields=["is_active", "sync_enabled"],
                name="calendar_in_is_acti_955806_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarintegration",
            index=models.Index(
                fields=["last_sync_at"], name="calendar_in_last_sy_c6ccf2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calendarintegration",
            unique_together={("organizer", "provider")},
        ),
        migrations.AddIndex(
            model_name="videoconferenceintegration",
            index=models.Index(
                fields=["is_active", "auto_generate_links"],
                name="video_integ_is_acti_229cb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoconferenceintegration",
            index=models.Index(
                fields=["rate_limit_reset_at"], name="video_integ_rate_li_bbd0cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videoconferenceintegration",
            unique_together={("organizer", "provider")},
        ),
    ]
